name: PHPUnit
on:
  - push
  - pull_request
jobs:
    phpunit:
        runs-on: ubuntu-latest
        name: PHPUnit
        steps:
            - name: Checkout
              uses: actions/checkout@v3.1.0
            - name: Composer dependencies
              uses: php-actions/composer@v6
              with:
                command: update
            - name: PHPUnit Tests
              uses: php-actions/phpunit@v9
              env:
                XDEBUG_MODE: coverage
              with:
                bootstrap: vendor/autoload.php
                configuration: phpunit.xml.dist
                php_extensions: xdebug
                args: tests --coverage-clover ./coverage.xml

            - name: Export to codecov
              uses: codecov/codecov-action@v3
              with:
                  fail_ci_if_error: true
                  token: ${{ secrets.CODE_COV_TOKEN }}
                  files: ./coverage.xml
                  verbose: true
